### ISSUE TITLE
Cannot use useLocales or getClientLocales

### ISSUE THREAD

**Issue by frontendphil** [sergiodxa/remix-utils#244]
### Describe the bug

The documentation lists these imports:

```ts
import { getClientLocales  } from 'remix-utils/get-client-locales'
import { useLocales } from 'remix-utils/use-locales'
```

However, these imports cannot be resolved. When I look at the `package.json` I see two different entries here: https://github.com/sergiodxa/remix-utils/blob/73b9bbbf05d94d53eb13edc995db6ee57576bf8d/package.json#L38

So I tried to this import: 

```ts
import { getClientLocales } from 'remix-utils/locales/server'
``` 

But that also does not seem to work (TS complains that it cannot find this export). This stuff used to work in `7.0.0-pre3`.

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

See description above.

### Expected behavior

The export should either match the docs or the docs should match the `package.json` and it should work :)

### Platform

- OS: macOS
- Browser: N/A
- Version: 7.0.1

**Comment by hilja** [comment]
I've got same with `import { eventStream } from 'remix-utils/sse/server'`:

```
Cannot find module 'remix-utils/sse/server' or its corresponding type declarations.
```

**Comment by hilja** [comment]
@sergiodxa Yeah I've got `serverModuleFormat: 'cjs'`, I had 'remix-utils' in `serverDependenciesToBundle`, but it gives the typical error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/antti/web/pagespeedlog/node_modules/.pnpm/remix-utils@7.0.1_@remix-run+node@2.0.1_@remix-run+react@2.0.1_react@18.2.0/node_modules/remix-utils/build/server/event-stream.js from /Users/bob/web/foo/build/index.js not supported.
Instead change the require of event-stream.js in /Users/bob/web/foo/build/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/antti/web/pagespeedlog/build/index.js:11998:22)
```

Then I put `remix-utils/sse/server` to `serverDependenciesToBundle` and that error is gone but it still can't find the module.

**Comment by sergiodxa** [comment]
@hilja did you added `"moduleResolution": "Bundler"` to your `tsconfig.json`?

**Comment by hilja** [comment]
Oh interesting, I was using what's in the [Blues Stack](https://github.com/remix-run/blues-stack/blob/main/tsconfig.json).

Now it find the module, but I still need to add `serverDependenciesToBundle: [ remix-utils/sse/server ]` for it to not error.

**Comment by sergiodxa** [comment]
Yeah if you use CJS you need the serverDependenciesToBundle, the change in tsconfig is needed for TS to correctly resolve the paths.

**Comment by hilja** [comment]
Cool, from reading the docs I was left with an impression that  `serverDependenciesToBundle: ["remix-utils"]` should be enough. Btw the docs say `import { eventStream } from "remix-utils/event-stream"`.
